services:
  api-identity-manager:
    image: ${IMAGE_REGISTRY:?}/${IMAGE_NAME_API_IDENTITY_MANAGER:?}:${IMAGE_VERSION_API_IDENTITY_MANAGER:?}
    env_file:
      - env/api-identity-manager.env
    environment:
      - COOG_URL=${COOG_INTERNAL_URL:?}
      - COOG_DB_NAME=${COOG_MAIN_DATABASE:?}
      - JWT_INTERNAL_ENCRYPTION=${JWT_INTERNAL_ENCRYPTION:?}

      - OPENTELEMETRY_ENABLED=${OPEN_TELEMETRY_TRACING_ENABLED:?}
      - OPENTELEMETRY_URL=${OPEN_TELEMETRY_TRACING_URL:-}
      - OPENTELEMETRY_TOKEN=${OPEN_TELEMETRY_TRACING_TOKEN:-}
      - OPENTELEMETRY_SERVICE_NAME=${OPEN_TELEMETRY_SERVICE_NAME_IDENTITY_MANAGER:?}

      - POSTGRESQL_URL=${POSTGRESQL_CONNECTION_STRING:?}
      - PGSSL=0

      - ENABLE_WINDOW_RATE_LIMIT=true
      - ENABLE_PERIODIC_RATE_LIMIT=true

      - COOG_MODULE=true
      - COOG_TOKEN_MODULE=true
      - ENABLE_API_KEY_AUTH=true

      - HAS_EXTERNAL_V3_SPEC=true
      - COOG_DEBUG_SERVER=true

    depends_on:
      - api
    restart: always
    networks:
      - backend
